In [19]:
# Pre-requisites
import numpy as np

# Writing a neural network in python

Firstly, a neural network is defined by the number of layers, and the number of neurons in each layer.

Let us use a list to denote this.

## Defining layer sizes

In [2]:
# Defining the sizes of the layers in our neural network
layers = [2, 2, 1]

The above code denotes the 3-neuron neural network we saw previously: 2-dimensional input, 2 neurons in a hidden layer, 1 neuron in the output layer.

Generally speaking, a neural network than has more than 1 hidden layer is a **deep** neural network.

## Defining weight matrices

Using the sizes of the layers in our neural network, let us initialize the weight matrices to random values (sampled from a standard normal gaussian, because we know that we need both positive and negative weights).

In [3]:
# Initializing weight matrices from layer sizes
def initializeWeights(layers):
    weights = [np.random.randn(o, i+1) for i, o in zip(layers[:-1], layers[1:])]
    return weights

In [4]:
# Displaying weight matrices
layers = [2, 2, 1]
weights = initializeWeights(layers)

for i in range(len(weights)):
    print(i+1); print(weights[i].shape); print(weights[i])

1
(2, 3)
[[-1.98719331  0.20618866 -0.3654309 ]
 [-1.06847288  0.85455326  0.24973183]]
2
(1, 3)
[[-0.85463231  0.67358712 -0.25368768]]


# Forward Propagation

The output of the neural network is calculated by **propagating forward** the outputs of each layer.

Let us define our input as an np.array, since we want to represent matrices.

In [9]:
# We shall use np.array() to represent matrices
#X = np.array([23, 42, 56])
X = np.array([[0,0], [0,1], [1,0], [1,1]])

## Adding bias terms

Since the input to every layer needs a bias term (1) added to it, let us define a function to do that.

In [10]:
# Add a bias term to every data point in the input
def addBiasTerms(X):
        # Make the input an np.array()
        X = np.array(X)
        
        # Forcing 1D vectors to be 2D matrices of 1xlength dimensions
        if X.ndim==1:
            X = np.reshape(X, (1, len(X)))
        
        # Inserting bias terms
        X = np.insert(X, 0, 1, axis=1)
        
        return X

Use the following cell to test the addBiasTerms function:

In [11]:
# TESTING addBiasTerms

# We shall use np.array() to represent matrices
#X = np.array([23, 42, 56])
X = np.array([[0,0], [0,1], [1,0], [1,1]])
print("Before adding bias terms: "); print(X)
X = addBiasTerms(X)
print("After adding bias terms: "); print(X)

Before adding bias terms: 
[[0 0]
 [0 1]
 [1 0]
 [1 1]]
After adding bias terms: 
[[1 0 0]
 [1 0 1]
 [1 1 0]
 [1 1 1]]


## Sigmoid function

Let us also define a function to calculate the sigmoid of any np.array given to it:

In [13]:
# Sigmoid function
def sigmoid(a):
    return 1/(1 + np.exp(-a))

## Forward propagation of inputs

Let us store the outputs of the layers in a list called "outputs". We shall use that the output of one layer as the input to the next layer.

In [17]:
# Forward Propagation of outputs
def forwardProp(X, weights):
    # Initializing an empty list of outputs
    outputs = []
    
    # Assigning a name to reuse as inputs
    inputs = X
    
    # For each layer
    for w in weights:
        # Add bias term to input
        inputs = addBiasTerms(inputs)
        
        # Y = Sigmoid ( X .* W^T )
        outputs.append(sigmoid(np.dot(inputs, w.T)))
        
        # Input of next layer is output of this layer
        inputs = outputs[-1]
        
    return outputs

Use the following cell to test forward propagation:

In [24]:
# VIEWING FORWARD PROPAGATION

# Initialize network
layers = [2, 2, 1]
#weights = initializeWeights(layers)

# 3-neuron network
weights = []
weights.append(np.array([[-250, 350, 350], [-250, 200, 200]]))
weights.append(np.array([[-100, 500, -500]]))

print("weights:")
for i in range(len(weights)):
    print(i+1); print(weights[i].shape); print(weights[i])

# Input
X = [[0,0], [0,1], [1,0], [1,1]]

print("X:"); print(X)

# Forward propagate X, and save outputs
outputs = forwardProp(X, weights)

print("outputs:")
for o in range(len(outputs)):
    print(o+1); print(outputs[o].shape); print(outputs[o])

weights:
1
(2, 3)
[[-250  350  350]
 [-250  200  200]]
2
(1, 3)
[[-100  500 -500]]
X:
[[0, 0], [0, 1], [1, 0], [1, 1]]
outputs:
1
(4, 2)
[[  2.66919022e-109   2.66919022e-109]
 [  1.00000000e+000   1.92874985e-022]
 [  1.00000000e+000   1.92874985e-022]
 [  1.00000000e+000   1.00000000e+000]]
2
(4, 1)
[[  3.72007598e-44]
 [  1.00000000e+00]
 [  1.00000000e+00]
 [  3.72007598e-44]]
